fold: 0  
model_name: efficientnet-b2
#initial model - if not exists, starts from imagenet pretreinded
model: model-b2-2.pth
#input image size: widthxwidth
width: 512
batch_size: 2
num_epochs: 5
#weight_decay: 0.000014712136461463032
weight_decay: 6.322983921368948e-7
#the source data dir with generated img.tif img_mask.png pairs
data_dir: D:\Classes\Year8\open-cities-ai-challenge-master\3rd\CCAP3
#directory with soft labeled data, pairs img.tif img_mask.png 
soft_labels_dir:  
debug: False
#?lodad optimizer state? 
load_state: 0
#max_lr: 0.0002259011271497254
max_lr: 0.0002
#some model tweaks (just attempt to bring some diversity to models ensamle)
use_attention: True
use_context_block: True
use_mish: True
#num workers for dataloader
num_workers: 1
#?online hard examples miming?
do_ohem: False
ref_scale: 0.07  
#noise in the model  
drop_connect_rate: 0.2 
use_over9000_optimizer: False

#web logging (tensorboad alternative)
use_neptune: False
neptune_user: xxx
neptune_project: xxx

hydra:
  run:
    # Output directory for normal runs
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
